dataset:
  script_path: ../datasets/normal_experiment.py
  length_std: 3.0
  length_mean: 20
  noise_std: 0.001
  length: 10000
  nb_past_steps: 30
  nb_future_steps: 1
  train_fraction: 0.6
  valid_fraction: 0.2
  test_fraction: 0.2
model:
  script_path: ../models/basic_lstm_independent_keras.py
  nb_lstm_states: 128
optimizer:
  script_path: ../optimizers/adam_keras.py
  learning_rate: 1e-5
loss_function:
  script_path: ../loss_functions/nll_keras.py
train:
  script_path: ../train/train_keras.py
  artifacts_path: ../artifacts/no_sensor_noise_medium_length_noise/
  batch_size: 128
  epochs: 10000
  patience: 100
  shuffle: True
  seed: 0
